// Generated by lib/script-interpreter/generator
// Auto generated file do not edit manually

#[derive(Clone, Debug)]
pub enum ExpressionStatement {
    AnyExpression(Box<crate::ast::any_expression::AnyExpression>),
    SemiColon(crate::token::Token),
    
}

impl ExpressionStatement {
    pub fn build_from_any_expression(any_expression: Box<crate::ast::any_expression::AnyExpression>) -> Self {
        ExpressionStatement::AnyExpression(any_expression)
    }
    pub fn build_from_semi_colon(semi_colon: crate::token::Token) -> Self {
        ExpressionStatement::SemiColon(semi_colon)
    }
}

impl crate::ast::expression::Expression for ExpressionStatement {
    fn accept(&self, visitor: Box<dyn crate::ast::visitor::Visitor>) {
        visitor.visit_expression_statement(self)
    }

}

