// Generated by tools/skills/main.rs
// Auto generated file do not edit manually

#![allow(dead_code)]

pub mod acolyte;
pub mod alchemist;
pub mod archer;
pub mod assassin;
pub mod assassincross;
pub mod baby;
pub mod bard;
pub mod blacksmith;
pub mod champion;
pub mod clown;
pub mod creator;
pub mod crusader;
pub mod dancer;
pub mod gunslinger;
pub mod gypsy;
pub mod highpriest;
pub mod highwizard;
pub mod hunter;
pub mod knight;
pub mod lordknight;
pub mod mage;
pub mod merchant;
pub mod monk;
pub mod ninja;
pub mod novice;
pub mod novicehigh;
pub mod paladin;
pub mod priest;
pub mod professor;
pub mod rogue;
pub mod sage;
pub mod sniper;
pub mod soul_linker;
pub mod stalker;
pub mod star_gladiator;
pub mod super_baby;
pub mod supernovice;
pub mod swordsman;
pub mod taekwon;
pub mod thief;
pub mod whitesmith;
pub mod wizard;
