use std::sync::mpsc::SyncSender;
use std::sync::{Arc, Once};
use models::enums::skill_enums::SkillEnum;
use models::enums::vanish::VanishType;
use models::enums::EnumWithNumberValue;
use packets::packets::PacketZcNotifyVanish;
use crate::repository::Repository;
use configuration::configuration::{Config, SkillConfig};
use crate::server::model::map::{Map, RANDOM_CELL};
use crate::server::model::events::client_notification::{AreaNotification, AreaNotificationRangeType, Notification};
use crate::server::model::events::persistence_event::PersistenceEvent;
use crate::server::Server;
use crate::server::service::server_service::ServerService;


static mut SERVICE_INSTANCE: Option<ScriptSkillService> = None;
static SERVICE_INSTANCE_INIT: Once = Once::new();

#[allow(dead_code)]
pub struct ScriptSkillService {
    client_notification_sender: SyncSender<Notification>,
    persistence_event_sender: SyncSender<PersistenceEvent>,
    repository: Arc<Repository>,
    configuration: &'static Config,
}

impl ScriptSkillService {
    pub fn instance() -> &'static ScriptSkillService {
        unsafe { SERVICE_INSTANCE.as_ref().unwrap() }
    }

    pub fn init(client_notification_sender: SyncSender<Notification>, persistence_event_sender: SyncSender<PersistenceEvent>, repository: Arc<Repository>, configuration: &'static Config) {
        SERVICE_INSTANCE_INIT.call_once(|| unsafe {
            SERVICE_INSTANCE = Some(ScriptSkillService { client_notification_sender, persistence_event_sender, repository, configuration });
        });
    }

    pub fn handle_skill(&self, server: &Server, skill: &SkillConfig, level: u32, _check_requirement: bool, source_char_id: u32) {
        let skill = SkillEnum::from_name(skill.name().as_str());
        let character_ref = server.state().get_character_unsafe(source_char_id);
        debug!("Handle skill {}, level {}", skill.to_name(), level);
        match skill {
            SkillEnum::NvBasic => {}
            SkillEnum::SmSword => {}
            SkillEnum::SmTwohand => {}
            SkillEnum::SmRecovery => {}
            SkillEnum::SmBash => {}
            SkillEnum::SmProvoke => {}
            SkillEnum::SmMagnum => {}
            SkillEnum::SmEndure => {}
            SkillEnum::MgSrecovery => {}
            SkillEnum::MgSight => {}
            SkillEnum::MgNapalmbeat => {}
            SkillEnum::MgSafetywall => {}
            SkillEnum::MgSoulstrike => {}
            SkillEnum::MgColdbolt => {}
            SkillEnum::MgFrostdiver => {}
            SkillEnum::MgStonecurse => {}
            SkillEnum::MgFireball => {}
            SkillEnum::MgFirewall => {}
            SkillEnum::MgFirebolt => {}
            SkillEnum::MgLightningbolt => {}
            SkillEnum::MgThunderstorm => {}
            SkillEnum::AlDp => {}
            SkillEnum::AlDemonbane => {}
            SkillEnum::AlRuwach => {}
            SkillEnum::AlPneuma => {}
            SkillEnum::AlTeleport => {
                if level == 1 {
                    ServerService::instance().schedule_warp_to_walkable_cell(server.state_mut().as_mut(), Map::name_without_ext(character_ref.current_map_name().as_str()).as_str(), RANDOM_CELL.0, RANDOM_CELL.1, source_char_id);
                    let mut packet_zc_notify_vanish = PacketZcNotifyVanish::new(self.configuration.packetver());
                    packet_zc_notify_vanish.set_gid(character_ref.char_id);
                    packet_zc_notify_vanish.set_atype(VanishType::Teleport.value() as u8);
                    packet_zc_notify_vanish.fill_raw();
                    server.client_notification_sender.send(Notification::Area(
                        AreaNotification::new(character_ref.current_map_name().clone(), character_ref.current_map_instance(),
                                              AreaNotificationRangeType::Fov { x: character_ref.x, y: character_ref.y, exclude_id: Some(character_ref.char_id) },
                                              packet_zc_notify_vanish.raw))).expect("Fail to send client notification");
                }
            }
            SkillEnum::AlWarp => {}
            SkillEnum::AlHeal => {}
            SkillEnum::AlIncagi => {}
            SkillEnum::AlDecagi => {}
            SkillEnum::AlHolywater => {}
            SkillEnum::AlCrucis => {}
            SkillEnum::AlAngelus => {}
            SkillEnum::AlBlessing => {}
            SkillEnum::AlCure => {}
            SkillEnum::McInccarry => {}
            SkillEnum::McDiscount => {}
            SkillEnum::McOvercharge => {}
            SkillEnum::McPushcart => {}
            SkillEnum::McIdentify => {}
            SkillEnum::McVending => {}
            SkillEnum::McMammonite => {}
            SkillEnum::AcOwl => {}
            SkillEnum::AcVulture => {}
            SkillEnum::AcConcentration => {}
            SkillEnum::AcDouble => {}
            SkillEnum::AcShower => {}
            SkillEnum::TfDouble => {}
            SkillEnum::TfMiss => {}
            SkillEnum::TfSteal => {}
            SkillEnum::TfHiding => {}
            SkillEnum::TfPoison => {}
            SkillEnum::TfDetoxify => {}
            SkillEnum::AllResurrection => {}
            SkillEnum::KnSpearmastery => {}
            SkillEnum::KnPierce => {}
            SkillEnum::KnBrandishspear => {}
            SkillEnum::KnSpearstab => {}
            SkillEnum::KnSpearboomerang => {}
            SkillEnum::KnTwohandquicken => {}
            SkillEnum::KnAutocounter => {}
            SkillEnum::KnBowlingbash => {}
            SkillEnum::KnRiding => {}
            SkillEnum::KnCavaliermastery => {}
            SkillEnum::PrMacemastery => {}
            SkillEnum::PrImpositio => {}
            SkillEnum::PrSuffragium => {}
            SkillEnum::PrAspersio => {}
            SkillEnum::PrBenedictio => {}
            SkillEnum::PrSanctuary => {}
            SkillEnum::PrSlowpoison => {}
            SkillEnum::PrStrecovery => {}
            SkillEnum::PrKyrie => {}
            SkillEnum::PrMagnificat => {}
            SkillEnum::PrGloria => {}
            SkillEnum::PrLexdivina => {}
            SkillEnum::PrTurnundead => {}
            SkillEnum::PrLexaeterna => {}
            SkillEnum::PrMagnus => {}
            SkillEnum::WzFirepillar => {}
            SkillEnum::WzSightrasher => {}
            SkillEnum::WzMeteor => {}
            SkillEnum::WzJupitel => {}
            SkillEnum::WzVermilion => {}
            SkillEnum::WzWaterball => {}
            SkillEnum::WzIcewall => {}
            SkillEnum::WzFrostnova => {}
            SkillEnum::WzStormgust => {}
            SkillEnum::WzEarthspike => {}
            SkillEnum::WzHeavendrive => {}
            SkillEnum::WzQuagmire => {}
            SkillEnum::WzEstimation => {}
            SkillEnum::BsIron => {}
            SkillEnum::BsSteel => {}
            SkillEnum::BsEnchantedstone => {}
            SkillEnum::BsOrideocon => {}
            SkillEnum::BsDagger => {}
            SkillEnum::BsSword => {}
            SkillEnum::BsTwohandsword => {}
            SkillEnum::BsAxe => {}
            SkillEnum::BsMace => {}
            SkillEnum::BsKnuckle => {}
            SkillEnum::BsSpear => {}
            SkillEnum::BsHiltbinding => {}
            SkillEnum::BsFindingore => {}
            SkillEnum::BsWeaponresearch => {}
            SkillEnum::BsRepairweapon => {}
            SkillEnum::BsSkintemper => {}
            SkillEnum::BsHammerfall => {}
            SkillEnum::BsAdrenaline => {}
            SkillEnum::BsWeaponperfect => {}
            SkillEnum::BsOverthrust => {}
            SkillEnum::BsMaximize => {}
            SkillEnum::HtSkidtrap => {}
            SkillEnum::HtLandmine => {}
            SkillEnum::HtAnklesnare => {}
            SkillEnum::HtShockwave => {}
            SkillEnum::HtSandman => {}
            SkillEnum::HtFlasher => {}
            SkillEnum::HtFreezingtrap => {}
            SkillEnum::HtBlastmine => {}
            SkillEnum::HtClaymoretrap => {}
            SkillEnum::HtRemovetrap => {}
            SkillEnum::HtTalkiebox => {}
            SkillEnum::HtBeastbane => {}
            SkillEnum::HtFalcon => {}
            SkillEnum::HtSteelcrow => {}
            SkillEnum::HtBlitzbeat => {}
            SkillEnum::HtDetecting => {}
            SkillEnum::HtSpringtrap => {}
            SkillEnum::AsRight => {}
            SkillEnum::AsLeft => {}
            SkillEnum::AsKatar => {}
            SkillEnum::AsCloaking => {}
            SkillEnum::AsSonicblow => {}
            SkillEnum::AsGrimtooth => {}
            SkillEnum::AsEnchantpoison => {}
            SkillEnum::AsPoisonreact => {}
            SkillEnum::AsVenomdust => {}
            SkillEnum::AsSplasher => {}
            SkillEnum::NvFirstaid => {}
            SkillEnum::NvTrickdead => {}
            SkillEnum::SmMovingrecovery => {}
            SkillEnum::SmFatalblow => {}
            SkillEnum::SmAutoberserk => {}
            SkillEnum::AcMakingarrow => {}
            SkillEnum::AcChargearrow => {}
            SkillEnum::TfSprinklesand => {}
            SkillEnum::TfBacksliding => {}
            SkillEnum::TfPickstone => {}
            SkillEnum::TfThrowstone => {}
            SkillEnum::McCartrevolution => {}
            SkillEnum::McChangecart => {}
            SkillEnum::McLoud => {}
            SkillEnum::AlHolylight => {}
            SkillEnum::MgEnergycoat => {}
            // SkillEnum::NpcPiercingatt => {}
            // SkillEnum::NpcMentalbreaker => {}
            // SkillEnum::NpcRangeattack => {}
            // SkillEnum::NpcAttrichange => {}
            // SkillEnum::NpcChangewater => {}
            // SkillEnum::NpcChangeground => {}
            // SkillEnum::NpcChangefire => {}
            // SkillEnum::NpcChangewind => {}
            // SkillEnum::NpcChangepoison => {}
            // SkillEnum::NpcChangeholy => {}
            // SkillEnum::NpcChangedarkness => {}
            // SkillEnum::NpcChangetelekinesis => {}
            // SkillEnum::NpcCriticalslash => {}
            // SkillEnum::NpcComboattack => {}
            // SkillEnum::NpcGuidedattack => {}
            // SkillEnum::NpcSelfdestruction => {}
            // SkillEnum::NpcSplashattack => {}
            // SkillEnum::NpcSuicide => {}
            // SkillEnum::NpcPoison => {}
            // SkillEnum::NpcBlindattack => {}
            // SkillEnum::NpcSilenceattack => {}
            // SkillEnum::NpcStunattack => {}
            // SkillEnum::NpcPetrifyattack => {}
            // SkillEnum::NpcCurseattack => {}
            // SkillEnum::NpcSleepattack => {}
            // SkillEnum::NpcRandomattack => {}
            // SkillEnum::NpcWaterattack => {}
            // SkillEnum::NpcGroundattack => {}
            // SkillEnum::NpcFireattack => {}
            // SkillEnum::NpcWindattack => {}
            // SkillEnum::NpcPoisonattack => {}
            // SkillEnum::NpcHolyattack => {}
            // SkillEnum::NpcDarknessattack => {}
            // SkillEnum::NpcTelekinesisattack => {}
            // SkillEnum::NpcMagicalattack => {}
            // SkillEnum::NpcMetamorphosis => {}
            // SkillEnum::NpcProvocation => {}
            // SkillEnum::NpcSmoking => {}
            // SkillEnum::NpcSummonslave => {}
            // SkillEnum::NpcEmotion => {}
            // SkillEnum::NpcTransformation => {}
            // SkillEnum::NpcBlooddrain => {}
            // SkillEnum::NpcEnergydrain => {}
            // SkillEnum::NpcKeeping => {}
            // SkillEnum::NpcDarkbreath => {}
            // SkillEnum::NpcDarkblessing => {}
            // SkillEnum::NpcBarrier => {}
            // SkillEnum::NpcDefender => {}
            // SkillEnum::NpcLick => {}
            // SkillEnum::NpcHallucination => {}
            // SkillEnum::NpcRebirth => {}
            // SkillEnum::NpcSummonmonster => {}
            SkillEnum::RgSnatcher => {}
            SkillEnum::RgStealcoin => {}
            SkillEnum::RgBackstap => {}
            SkillEnum::RgTunneldrive => {}
            SkillEnum::RgRaid => {}
            SkillEnum::RgStripweapon => {}
            SkillEnum::RgStripshield => {}
            SkillEnum::RgStriparmor => {}
            SkillEnum::RgStriphelm => {}
            SkillEnum::RgIntimidate => {}
            SkillEnum::RgGraffiti => {}
            SkillEnum::RgFlaggraffiti => {}
            SkillEnum::RgCleaner => {}
            SkillEnum::RgGangster => {}
            SkillEnum::RgCompulsion => {}
            SkillEnum::RgPlagiarism => {}
            SkillEnum::AmAxemastery => {}
            SkillEnum::AmLearningpotion => {}
            SkillEnum::AmPharmacy => {}
            SkillEnum::AmDemonstration => {}
            SkillEnum::AmAcidterror => {}
            SkillEnum::AmPotionpitcher => {}
            SkillEnum::AmCannibalize => {}
            SkillEnum::AmSpheremine => {}
            SkillEnum::AmCpWeapon => {}
            SkillEnum::AmCpShield => {}
            SkillEnum::AmCpArmor => {}
            SkillEnum::AmCpHelm => {}
            SkillEnum::AmBioethics => {}
            SkillEnum::AmCallhomun => {}
            SkillEnum::AmRest => {}
            SkillEnum::AmResurrecthomun => {}
            SkillEnum::CrTrust => {}
            SkillEnum::CrAutoguard => {}
            SkillEnum::CrShieldcharge => {}
            SkillEnum::CrShieldboomerang => {}
            SkillEnum::CrReflectshield => {}
            SkillEnum::CrHolycross => {}
            SkillEnum::CrGrandcross => {}
            SkillEnum::CrDevotion => {}
            SkillEnum::CrProvidence => {}
            SkillEnum::CrDefender => {}
            SkillEnum::CrSpearquicken => {}
            SkillEnum::MoIronhand => {}
            SkillEnum::MoSpiritsrecovery => {}
            SkillEnum::MoCallspirits => {}
            SkillEnum::MoAbsorbspirits => {}
            SkillEnum::MoTripleattack => {}
            SkillEnum::MoBodyrelocation => {}
            SkillEnum::MoDodge => {}
            SkillEnum::MoInvestigate => {}
            SkillEnum::MoFingeroffensive => {}
            SkillEnum::MoSteelbody => {}
            SkillEnum::MoBladestop => {}
            SkillEnum::MoExplosionspirits => {}
            SkillEnum::MoExtremityfist => {}
            SkillEnum::MoChaincombo => {}
            SkillEnum::MoCombofinish => {}
            SkillEnum::SaAdvancedbook => {}
            SkillEnum::SaCastcancel => {}
            SkillEnum::SaMagicrod => {}
            SkillEnum::SaSpellbreaker => {}
            SkillEnum::SaFreecast => {}
            SkillEnum::SaAutospell => {}
            SkillEnum::SaFlamelauncher => {}
            SkillEnum::SaFrostweapon => {}
            SkillEnum::SaLightningloader => {}
            SkillEnum::SaSeismicweapon => {}
            SkillEnum::SaDragonology => {}
            SkillEnum::SaVolcano => {}
            SkillEnum::SaDeluge => {}
            SkillEnum::SaViolentgale => {}
            SkillEnum::SaLandprotector => {}
            SkillEnum::SaDispell => {}
            SkillEnum::SaAbracadabra => {}
            SkillEnum::SaMonocell => {}
            SkillEnum::SaClasschange => {}
            SkillEnum::SaSummonmonster => {}
            SkillEnum::SaReverseorcish => {}
            SkillEnum::SaDeath => {}
            SkillEnum::SaFortune => {}
            SkillEnum::SaTamingmonster => {}
            SkillEnum::SaQuestion => {}
            SkillEnum::SaGravity => {}
            SkillEnum::SaLevelup => {}
            SkillEnum::SaInstantdeath => {}
            SkillEnum::SaFullrecovery => {}
            SkillEnum::SaComa => {}
            SkillEnum::BdAdaptation => {}
            SkillEnum::BdEncore => {}
            SkillEnum::BdLullaby => {}
            SkillEnum::BdRichmankim => {}
            SkillEnum::BdEternalchaos => {}
            SkillEnum::BdDrumbattlefield => {}
            SkillEnum::BdRingnibelungen => {}
            SkillEnum::BdRokisweil => {}
            SkillEnum::BdIntoabyss => {}
            SkillEnum::BdSiegfried => {}
            SkillEnum::BaMusicallesson => {}
            SkillEnum::BaMusicalstrike => {}
            SkillEnum::BaDissonance => {}
            SkillEnum::BaFrostjoker => {}
            SkillEnum::BaWhistle => {}
            SkillEnum::BaAssassincross => {}
            SkillEnum::BaPoembragi => {}
            SkillEnum::BaAppleidun => {}
            SkillEnum::DcDancinglesson => {}
            SkillEnum::DcThrowarrow => {}
            SkillEnum::DcUglydance => {}
            SkillEnum::DcScream => {}
            SkillEnum::DcHumming => {}
            SkillEnum::DcDontforgetme => {}
            SkillEnum::DcFortunekiss => {}
            SkillEnum::DcServiceforyou => {}
            // SkillEnum::NpcRandommove => {}
            // SkillEnum::NpcSpeedup => {}
            // SkillEnum::NpcRevenge => {}
            SkillEnum::WeMale => {}
            SkillEnum::WeFemale => {}
            SkillEnum::WeCallpartner => {}
            SkillEnum::ItmTomahawk => {}
            // SkillEnum::NpcDarkcross => {}
            // SkillEnum::NpcGranddarkness => {}
            // SkillEnum::NpcDarkstrike => {}
            // SkillEnum::NpcDarkthunder => {}
            // SkillEnum::NpcStop => {}
            // SkillEnum::NpcWeaponbraker => {}
            // SkillEnum::NpcArmorbrake => {}
            // SkillEnum::NpcHelmbrake => {}
            // SkillEnum::NpcShieldbrake => {}
            // SkillEnum::NpcUndeadattack => {}
            // SkillEnum::NpcChangeundead => {}
            // SkillEnum::NpcPowerup => {}
            // SkillEnum::NpcAgiup => {}
            // SkillEnum::NpcSiegemode => {}
            // SkillEnum::NpcCallslave => {}
            // SkillEnum::NpcInvisible => {}
            // SkillEnum::NpcRun => {}
            SkillEnum::LkAurablade => {}
            SkillEnum::LkParrying => {}
            SkillEnum::LkConcentration => {}
            SkillEnum::LkTensionrelax => {}
            SkillEnum::LkBerserk => {}
            SkillEnum::LkFury => {}
            SkillEnum::HpAssumptio => {}
            SkillEnum::HpBasilica => {}
            SkillEnum::HpMeditatio => {}
            SkillEnum::HwSouldrain => {}
            SkillEnum::HwMagiccrasher => {}
            SkillEnum::HwMagicpower => {}
            SkillEnum::PaPressure => {}
            SkillEnum::PaSacrifice => {}
            SkillEnum::PaGospel => {}
            SkillEnum::ChPalmstrike => {}
            SkillEnum::ChTigerfist => {}
            SkillEnum::ChChaincrush => {}
            SkillEnum::PfHpconversion => {}
            SkillEnum::PfSoulchange => {}
            SkillEnum::PfSoulburn => {}
            SkillEnum::AscKatar => {}
            SkillEnum::AscEdp => {}
            SkillEnum::AscBreaker => {}
            SkillEnum::SnSight => {}
            SkillEnum::SnFalconassault => {}
            SkillEnum::SnSharpshooting => {}
            SkillEnum::SnWindwalk => {}
            SkillEnum::WsMeltdown => {}
            SkillEnum::WsCreatecoin => {}
            SkillEnum::WsCreatenugget => {}
            SkillEnum::WsCartboost => {}
            SkillEnum::WsSystemcreate => {}
            SkillEnum::StChasewalk => {}
            SkillEnum::StRejectsword => {}
            SkillEnum::CrAlchemy => {}
            SkillEnum::CrSynthesispotion => {}
            SkillEnum::CgArrowvulcan => {}
            SkillEnum::CgMoonlit => {}
            SkillEnum::CgMarionette => {}
            SkillEnum::LkSpiralpierce => {}
            SkillEnum::LkHeadcrush => {}
            SkillEnum::LkJointbeat => {}
            SkillEnum::HwNapalmvulcan => {}
            SkillEnum::ChSoulcollect => {}
            SkillEnum::PfMindbreaker => {}
            SkillEnum::PfMemorize => {}
            SkillEnum::PfFogwall => {}
            SkillEnum::PfSpiderweb => {}
            SkillEnum::AscMeteorassault => {}
            SkillEnum::AscCdp => {}
            SkillEnum::WeBaby => {}
            SkillEnum::WeCallparent => {}
            SkillEnum::WeCallbaby => {}
            SkillEnum::TkRun => {}
            SkillEnum::TkReadystorm => {}
            SkillEnum::TkStormkick => {}
            SkillEnum::TkReadydown => {}
            SkillEnum::TkDownkick => {}
            SkillEnum::TkReadyturn => {}
            SkillEnum::TkTurnkick => {}
            SkillEnum::TkReadycounter => {}
            SkillEnum::TkCounter => {}
            SkillEnum::TkDodge => {}
            SkillEnum::TkJumpkick => {}
            SkillEnum::TkHptime => {}
            SkillEnum::TkSptime => {}
            SkillEnum::TkPower => {}
            SkillEnum::TkSevenwind => {}
            SkillEnum::TkHighjump => {}
            SkillEnum::SgFeel => {}
            SkillEnum::SgSunWarm => {}
            SkillEnum::SgMoonWarm => {}
            SkillEnum::SgStarWarm => {}
            SkillEnum::SgSunComfort => {}
            SkillEnum::SgMoonComfort => {}
            SkillEnum::SgStarComfort => {}
            SkillEnum::SgHate => {}
            SkillEnum::SgSunAnger => {}
            SkillEnum::SgMoonAnger => {}
            SkillEnum::SgStarAnger => {}
            SkillEnum::SgSunBless => {}
            SkillEnum::SgMoonBless => {}
            SkillEnum::SgStarBless => {}
            SkillEnum::SgDevil => {}
            SkillEnum::SgFriend => {}
            SkillEnum::SgKnowledge => {}
            SkillEnum::SgFusion => {}
            SkillEnum::SlAlchemist => {}
            SkillEnum::AmBerserkpitcher => {}
            SkillEnum::SlMonk => {}
            SkillEnum::SlStar => {}
            SkillEnum::SlSage => {}
            SkillEnum::SlCrusader => {}
            SkillEnum::SlSupernovice => {}
            SkillEnum::SlKnight => {}
            SkillEnum::SlWizard => {}
            SkillEnum::SlPriest => {}
            SkillEnum::SlBarddancer => {}
            SkillEnum::SlRogue => {}
            SkillEnum::SlAssasin => {}
            SkillEnum::SlBlacksmith => {}
            SkillEnum::BsAdrenaline2 => {}
            SkillEnum::SlHunter => {}
            SkillEnum::SlSoullinker => {}
            SkillEnum::SlKaizel => {}
            SkillEnum::SlKaahi => {}
            SkillEnum::SlKaupe => {}
            SkillEnum::SlKaite => {}
            SkillEnum::SlKaina => {}
            SkillEnum::SlStin => {}
            SkillEnum::SlStun => {}
            SkillEnum::SlSma => {}
            SkillEnum::SlSwoo => {}
            SkillEnum::SlSke => {}
            SkillEnum::SlSka => {}
            SkillEnum::SmSelfprovoke => {}
            // SkillEnum::NpcEmotionOn => {}
            SkillEnum::StPreserve => {}
            SkillEnum::StFullstrip => {}
            SkillEnum::WsWeaponrefine => {}
            SkillEnum::CrSlimpitcher => {}
            SkillEnum::CrFullprotection => {}
            SkillEnum::PaShieldchain => {}
            SkillEnum::HpManarecharge => {}
            SkillEnum::PfDoublecasting => {}
            SkillEnum::HwGanbantein => {}
            SkillEnum::HwGravitation => {}
            SkillEnum::WsCarttermination => {}
            SkillEnum::WsOverthrustmax => {}
            SkillEnum::CgLongingfreedom => {}
            SkillEnum::CgHermode => {}
            SkillEnum::CgTarotcard => {}
            SkillEnum::CrAciddemonstration => {}
            SkillEnum::CrCultivation => {}
            SkillEnum::ItemEnchantarms => {}
            SkillEnum::TkMission => {}
            SkillEnum::SlHigh => {}
            SkillEnum::KnOnehand => {}
            SkillEnum::AmTwilight1 => {}
            SkillEnum::AmTwilight2 => {}
            SkillEnum::AmTwilight3 => {}
            SkillEnum::HtPower => {}
            SkillEnum::GsGlittering => {}
            SkillEnum::GsFling => {}
            SkillEnum::GsTripleaction => {}
            SkillEnum::GsBullseye => {}
            SkillEnum::GsMadnesscancel => {}
            SkillEnum::GsAdjustment => {}
            SkillEnum::GsIncreasing => {}
            SkillEnum::GsMagicalbullet => {}
            SkillEnum::GsCracker => {}
            SkillEnum::GsSingleaction => {}
            SkillEnum::GsSnakeeye => {}
            SkillEnum::GsChainaction => {}
            SkillEnum::GsTracking => {}
            SkillEnum::GsDisarm => {}
            SkillEnum::GsPiercingshot => {}
            SkillEnum::GsRapidshower => {}
            SkillEnum::GsDesperado => {}
            SkillEnum::GsGatlingfever => {}
            SkillEnum::GsDust => {}
            SkillEnum::GsFullbuster => {}
            SkillEnum::GsSpreadattack => {}
            SkillEnum::GsGrounddrift => {}
            SkillEnum::NjTobidougu => {}
            SkillEnum::NjSyuriken => {}
            SkillEnum::NjKunai => {}
            SkillEnum::NjHuuma => {}
            SkillEnum::NjZenynage => {}
            SkillEnum::NjTatamigaeshi => {}
            SkillEnum::NjKasumikiri => {}
            SkillEnum::NjShadowjump => {}
            SkillEnum::NjKirikage => {}
            SkillEnum::NjUtsusemi => {}
            SkillEnum::NjBunsinjyutsu => {}
            SkillEnum::NjNinpou => {}
            SkillEnum::NjKouenka => {}
            SkillEnum::NjKaensin => {}
            SkillEnum::NjBakuenryu => {}
            SkillEnum::NjHyousensou => {}
            SkillEnum::NjSuiton => {}
            SkillEnum::NjHyousyouraku => {}
            SkillEnum::NjHuujin => {}
            SkillEnum::NjRaigekisai => {}
            SkillEnum::NjKamaitachi => {}
            SkillEnum::NjNen => {}
            SkillEnum::NjIssen => {}
            SkillEnum::SlDeathknight => {}
            SkillEnum::SlCollector => {}
            SkillEnum::SlNinja => {}
            SkillEnum::SlGunner => {}
            // SkillEnum::NpcEarthquake => {}
            // SkillEnum::NpcFirebreath => {}
            // SkillEnum::NpcIcebreath => {}
            // SkillEnum::NpcThunderbreath => {}
            // SkillEnum::NpcAcidbreath => {}
            // SkillEnum::NpcDarknessbreath => {}
            // SkillEnum::NpcDragonfear => {}
            // SkillEnum::NpcBleeding => {}
            // SkillEnum::NpcPulsestrike => {}
            // SkillEnum::NpcHelljudgement => {}
            // SkillEnum::NpcWidesilence => {}
            // SkillEnum::NpcWidefreeze => {}
            // SkillEnum::NpcWidebleeding => {}
            // SkillEnum::NpcWidestone => {}
            // SkillEnum::NpcWideconfuse => {}
            // SkillEnum::NpcWidesleep => {}
            // SkillEnum::NpcWidesight => {}
            // SkillEnum::NpcEvilland => {}
            // SkillEnum::NpcMagicmirror => {}
            // SkillEnum::NpcSlowcast => {}
            // SkillEnum::NpcCriticalwound => {}
            // SkillEnum::NpcExpulsion => {}
            // SkillEnum::NpcStoneskin => {}
            // SkillEnum::NpcAntimagic => {}
            // SkillEnum::NpcWidecurse => {}
            // SkillEnum::NpcWidestun => {}
            // SkillEnum::NpcVampireGift => {}
            // SkillEnum::NpcWidesouldrain => {}
            SkillEnum::AllInccarry => {}
            // SkillEnum::NpcTalk => {}
            // SkillEnum::NpcHellpower => {}
            // SkillEnum::NpcWidehelldignity => {}
            // SkillEnum::NpcInvincible => {}
            // SkillEnum::NpcInvincibleoff => {}
            // SkillEnum::NpcAllheal => {}
            SkillEnum::GmSandman => {}
            SkillEnum::CashBlessing => {}
            SkillEnum::CashIncagi => {}
            SkillEnum::CashAssumptio => {}
            SkillEnum::AllCatcry => {}
            SkillEnum::AllPartyflee => {}
            SkillEnum::AllDreamSummernight => {}
            SkillEnum::AllReverseorcish => {}
            SkillEnum::AllWewish => {}
            // SkillEnum::NpcVenomfog => {}
            // SkillEnum::NpcComet => {}
            // SkillEnum::NpcMaxpain => {}
            // SkillEnum::NpcMaxpainAtk => {}
            // SkillEnum::NpcJackfrost => {}
            // SkillEnum::NpcReverberation => {}
            // SkillEnum::NpcReverberationAtk => {}
            // SkillEnum::NpcLexAeterna => {}
            // SkillEnum::NpcArrowstorm => {}
            // SkillEnum::NpcCloudKill => {}
            // SkillEnum::NpcIgnitionbreak => {}
            // SkillEnum::NpcPhantomthrust => {}
            // SkillEnum::NpcPoisonBuster => {}
            // SkillEnum::NpcHallucinationwalk => {}
            // SkillEnum::NpcElectricwalk => {}
            // SkillEnum::NpcFirewalk => {}
            SkillEnum::KnChargeatk => {}
            SkillEnum::CrShrink => {}
            SkillEnum::AsSonicaccel => {}
            SkillEnum::AsVenomknife => {}
            SkillEnum::RgCloseconfine => {}
            SkillEnum::WzSightblaster => {}
            SkillEnum::SaCreatecon => {}
            SkillEnum::SaElementwater => {}
            SkillEnum::HtPhantasmic => {}
            SkillEnum::BaPangvoice => {}
            SkillEnum::DcWinkcharm => {}
            SkillEnum::BsUnfairlytrick => {}
            SkillEnum::BsGreed => {}
            SkillEnum::PrRedemptio => {}
            SkillEnum::MoKitranslation => {}
            SkillEnum::MoBalkyoung => {}
            SkillEnum::SaElementground => {}
            SkillEnum::SaElementfire => {}
            SkillEnum::SaElementwind => {}
            SkillEnum::HlifHeal => {}
            SkillEnum::HlifAvoid => {}
            SkillEnum::HlifBrain => {}
            SkillEnum::HlifChange => {}
            SkillEnum::HamiCastle => {}
            SkillEnum::HamiDefence => {}
            SkillEnum::HamiSkin => {}
            SkillEnum::HamiBloodlust => {}
            SkillEnum::HfliMoon => {}
            SkillEnum::HfliFleet => {}
            SkillEnum::HfliSpeed => {}
            SkillEnum::HfliSbr44 => {}
            SkillEnum::HvanCaprice => {}
            SkillEnum::HvanChaotic => {}
            SkillEnum::HvanInstruct => {}
            SkillEnum::HvanExplosion => {}
            SkillEnum::MhSummonLegion => {}
            SkillEnum::MhNeedleOfParalyze => {}
            SkillEnum::MhPoisonMist => {}
            SkillEnum::MhPainKiller => {}
            SkillEnum::MhLightOfRegene => {}
            SkillEnum::MhOveredBoost => {}
            SkillEnum::MhEraserCutter => {}
            SkillEnum::MhXenoSlasher => {}
            SkillEnum::MhSilentBreeze => {}
            SkillEnum::MhStyleChange => {}
            SkillEnum::MhSonicCraw => {}
            SkillEnum::MhSilverveinRush => {}
            SkillEnum::MhMidnightFrenzy => {}
            SkillEnum::MhStahlHorn => {}
            SkillEnum::MhGoldeneFerse => {}
            SkillEnum::MhSteinwand => {}
            SkillEnum::MhHeiligeStange => {}
            SkillEnum::MhAngriffsModus => {}
            SkillEnum::MhTinderBreaker => {}
            SkillEnum::MhCbc => {}
            SkillEnum::MhEqc => {}
            SkillEnum::MhMagmaFlow => {}
            SkillEnum::MhGraniticArmor => {}
            SkillEnum::MhLavaSlide => {}
            SkillEnum::MhPyroclastic => {}
            SkillEnum::MhVolcanicAsh => {}
            SkillEnum::MsBash => {}
            SkillEnum::MsMagnum => {}
            SkillEnum::MsBowlingbash => {}
            SkillEnum::MsParrying => {}
            SkillEnum::MsReflectshield => {}
            SkillEnum::MsBerserk => {}
            SkillEnum::MaDouble => {}
            SkillEnum::MaShower => {}
            SkillEnum::MaSkidtrap => {}
            SkillEnum::MaLandmine => {}
            SkillEnum::MaSandman => {}
            SkillEnum::MaFreezingtrap => {}
            SkillEnum::MaRemovetrap => {}
            SkillEnum::MaChargearrow => {}
            SkillEnum::MaSharpshooting => {}
            SkillEnum::MlPierce => {}
            SkillEnum::MlBrandish => {}
            SkillEnum::MlSpiralpierce => {}
            SkillEnum::MlDefender => {}
            SkillEnum::MlAutoguard => {}
            SkillEnum::MlDevotion => {}
            SkillEnum::MerMagnificat => {}
            SkillEnum::MerQuicken => {}
            SkillEnum::MerSight => {}
            SkillEnum::MerCrash => {}
            SkillEnum::MerRegain => {}
            SkillEnum::MerTender => {}
            SkillEnum::MerBenediction => {}
            SkillEnum::MerRecuperate => {}
            SkillEnum::MerMentalcure => {}
            SkillEnum::MerCompress => {}
            SkillEnum::MerProvoke => {}
            SkillEnum::MerAutoberserk => {}
            SkillEnum::MerDecagi => {}
            SkillEnum::MerScapegoat => {}
            SkillEnum::MerLexdivina => {}
            SkillEnum::MerEstimation => {}
            SkillEnum::MerKyrie => {}
            SkillEnum::MerBlessing => {}
            SkillEnum::MerIncagi => {}
            SkillEnum::MerInvincibleoff2 => {}
            SkillEnum::ElCircleOfFire => {}
            SkillEnum::ElFireCloak => {}
            SkillEnum::ElFireMantle => {}
            SkillEnum::ElWaterScreen => {}
            SkillEnum::ElWaterDrop => {}
            SkillEnum::ElWaterBarrier => {}
            SkillEnum::ElWindStep => {}
            SkillEnum::ElWindCurtain => {}
            SkillEnum::ElZephyr => {}
            SkillEnum::ElSolidSkin => {}
            SkillEnum::ElStoneShield => {}
            SkillEnum::ElPowerOfGaia => {}
            SkillEnum::ElPyrotechnic => {}
            SkillEnum::ElHeater => {}
            SkillEnum::ElTropic => {}
            SkillEnum::ElAquaplay => {}
            SkillEnum::ElCooler => {}
            SkillEnum::ElChillyAir => {}
            SkillEnum::ElGust => {}
            SkillEnum::ElBlast => {}
            SkillEnum::ElWildStorm => {}
            SkillEnum::ElPetrology => {}
            SkillEnum::ElCursedSoil => {}
            SkillEnum::ElUpheaval => {}
            SkillEnum::ElFireArrow => {}
            SkillEnum::ElFireBomb => {}
            SkillEnum::ElFireBombAtk => {}
            SkillEnum::ElFireWave => {}
            SkillEnum::ElFireWaveAtk => {}
            SkillEnum::ElIceNeedle => {}
            SkillEnum::ElWaterScrew => {}
            SkillEnum::ElWaterScrewAtk => {}
            SkillEnum::ElTidalWeapon => {}
            SkillEnum::ElWindSlash => {}
            SkillEnum::ElHurricane => {}
            SkillEnum::ElHurricaneAtk => {}
            SkillEnum::ElTypoonMis => {}
            SkillEnum::ElTypoonMisAtk => {}
            SkillEnum::ElStoneHammer => {}
            SkillEnum::ElRockCrusher => {}
            SkillEnum::ElRockCrusherAtk => {}
            SkillEnum::ElStoneRain => {}
            SkillEnum::GdApproval => {}
            SkillEnum::GdKafracontract => {}
            SkillEnum::GdGuardresearch => {}
            SkillEnum::GdGuardup => {}
            SkillEnum::GdExtension => {}
            SkillEnum::GdGloryguild => {}
            SkillEnum::GdLeadership => {}
            SkillEnum::GdGlorywounds => {}
            SkillEnum::GdSoulcold => {}
            SkillEnum::GdHawkeyes => {}
            SkillEnum::GdBattleorder => {}
            SkillEnum::GdRegeneration => {}
            SkillEnum::GdRestore => {}
            SkillEnum::GdEmergencycall => {}
            SkillEnum::GdDevelopment => {}
            SkillEnum::GdItememergencycall => {}
        }
    }
}