{ // JobNames
JobName = [
["","Novice"]
,["","Swordman"]
,["","Thief"]
,["","Acolyte"]
,["","Archer"]
,["","Mage"]
,["","Merchant"]
,["","Knight"]
,["","Assassin"]
,["","Priest"]
,["","Hunter"]
,["","Wizard"]
,["","Blacksmith"]
,["","Crusader"]
,["","Rogue"]
,["","Monk"]
,["","Bard"]
,["","Dancer"]
,["","Sage"]
,["","Alchemist"]
,["","Super Novice"]
,["","Lord Knight"]
,["","Assassin Cross"]
,["","High Priest"]
,["","Sniper"]
,["","High Wizard"]
,["","Mastersmith"]
,["","Paladin"]
,["","Stalker"]
,["","Champion"]
,["","Minstrel"]
,["","Gypsy"]
,["","Scholar"]
,["","Biochemist"]
,["","High Novice"]
,["","High Swordman"]
,["","High Thief"]
,["","High Acolyte"]
,["","High Archer"]
,["","High Magician"]
,["","High Merchant"]
,["","Taekwon Kid"]
,["","Teakwon Master"]
,["","Soul Linker"]
,["","Ninja"]
,["","Gunslinger"]
,["","Rune Knight (non-trans)"]
,["","Rune Knight (trans)"]
,["","Glt Cross (non-trans)"]
,["","Glt Cross (trans)"]
,["","Arch Bishop (non-trans)"]
,["","Arch Bishop (trans)"]
,["","Ranger (non-trans)"]
,["","Ranger (trans)"]
,["","Warlock (non-trans)"]
,["","Warlock (trans)"]
,["","Mechanic (non-trans)"]
,["","Mechanic (trans)"]
,["","Royal Guard (non-trans)"]
,["","Royal Guard (trans)"]
,["","Shadow Chaser (non-trans)"]
,["","Shadow Chaser (trans)"]
,["","Sura (non-trans)"]
,["","Sura (trans)"]
,["","Maestro (non-trans)"]
,["","Maestro (trans)"]
,["","Wanderer (non-trans)"]
,["","Wanderer (trans)"]
,["","Sorcerer (non-trans)"]
,["","Sorcerer (trans)"]
,["","Geneticist (non-trans)"]
,["","Geneticist (trans)"]
,["","Kagero/Oboro"]
,["","Expanded Super Novice"]
];
}
