{ // MapNames
MAP_NAME = [
["","All Maps"]
,["","Prontera Fields"]
,["","Prontera Culvert"]
,["","Labyrinth Forest"]
,["","Undersea Tunnel"]
,["","Morocc Fields"]
,["","Pyramid Dungeon"]
,["","Sphinx Dungeon"]
,["","Ant Hell"]
,["","Geffen Fields"]
,["","Geffen Dungeon"]
,["","Geffenia"]
,["","Orc Dungeon"]
,["","Glast Heim"]
,["","Glast Heim Lower"]
,["","Poring Island"]
,["","Payon Fields"]
,["","Payon Cave"]
,["��","Sunken Ship"]
,["","Mjolnir Fields"]
,["","Mjolnir Dead Pit"]
,["","Clock Tower"]
,["","Toy Factory"]
,["","Comodo Fields"]
,["","Comodo Dungeon"]
,["","Umbala Fields"]
,["","Umbala Dungeon"]
,["","Nifflheim Fields"]
,["","Guild Dungeons Baldur"]
,["","Guild Dungeons Luina"]
,["","Guild Dungeons Valkyrie"]
,["","Guild Dungeons Britoniah"]
,["","Turtle Dungeon"]
,["","Amatsu"]
,["","Kunlun"]
,["��","Louyang"]
,["","Ayotaya"]
,["","Juno Fields"]
,["","Magma Dungeon"]
,["","Doll Factory"]
,["","Einbroch Fields"]
,["","Mine Dungeon"]
,["","Lighthalzen Fields"]
,["","Somatology Laboratory"]
,["","Ruins of Juperos"]
,["","Hugel Fields"]
,["","Abyss Lake"]
,["","Thanatos Tower"]
,["","Odin Temple"]
,["","Rachel Fields"]
,["","Rachel Sanctuary"]
,["�","Ice Dungeon"]
,["","Veins Fields"]
,["","Thor Volcano"]
,["","Nameless Island"]
,["","Moscovia"]
,["��","Between Dimensions"]
,["","Guild Dungeons (Juno)"]
,["","Guild Dungeons (Rachel)"]
,["","Endless Tower"]
,["","Another world"]
,["","Nidhoggur Dungeon"]
,["","Outskirts of Kamidal Mountain"]
,["","Kamidal Tunnel"]
,["","Scaraba Hall"]
,["","Brasilis Field"]
,["","Brasilis Dungeon"]
,["","Overlook Water Dungeon"]
,["","Dewata"]
];
}
