{ // SkillNames
SKILL_NAME = [
["","Basic Attack"]
,["","First Aid"]
,["","Play Dead"]
,["","Sword Mastery"]
,["","Two-Hand Sword Mastery"]
,["","Increased HP Recovery"]
,["","Bash"]
,["","Magnum Break"]
,["","Provoke"]
,["","Endure"]
,["","HP Recovery While Moving"]
,["","Fatal Blow"]
,["","Auto Berserk"]
,["","Double Attack"]
,["","Improve Dodge"]
,["","Steal"]
,["","Hiding"]
,["","Envenom"]
,["","Detoxify"]
,["","Sand Attack"]
,["","Back Slide"]
,["","Find Stone"]
,["","Stone Fling"]
,["","Divine Protection"]
,["","Demon Bane"]
,["","Heal"]
,["","Cure"]
,["","Increase AGI"]
,["","Decrease AGI"]
,["","Signum Crusis"]
,["","Angelus"]
,["","Blessing"]
,["","Pneuma"]
,["","Aqua Benedicta"]
,["","Ruwach"]
,["","Teleport"]
,["","Warp Portal"]
,["","Holy Light"]
,["","Owl's Eye"]
,["","Vulture's Eye"]
,["","Double Strafe"]
,["","Arrow Shower"]
,["","Improve Concentration"]
,["","Arrow Crafting"]
,["","Arrow Repel"]
,["","Increased SP Recovery"]
,["","Napalm Beat"]
,["","Soul Strike"]
,["","Safety Wall"]
,["","Stone Curse"]
,["","Sight"]
,["","Fire Bolt"]
,["","Fire Ball"]
,["","Fire Wall"]
,["","Cold Bolt"]
,["","Frost Diver"]
,["","Lightning Bolt"]
,["","Thunder Storm"]
,["","Energy Coat"]
,["","Enlarge Weight Limit"]
,["","Discount"]
,["","Overcharge"]
,["","Pushcart"]
,["","Item Appraisal"]
,["","Vending"]
,["","Mammonite"]
,["","Cart Revolution"]
,["","Change Cart"]
,["","Crazy Uproar"]
,["","Spear Mastery"]
,["","Pierce"]
,["","Spear Stab"]
,["","Spear Boomerang"]
,["","Brandish Spear"]
,["","Twohand Quicken"]
,["","Auto Counter"]
,["","Bowling Bash"]
,["","Peco Peco Ride"]
,["","Cavalier Mastery"]
,["","Righthand Mastery"]
,["","Lefthand Mastery"]
,["","Katar Mastery"]
,["","Cloaking"]
,["","Sonic Blow"]
,["","Grimtooth"]
,["","Enchant Poison"]
,["","Poison React (Counter)"]
,["","Venom Dust"]
,["","Venom Splasher"]
,["","Mace Mastery"]
,["","Impositio Manus"]
,["","Suffragium"]
,["","Aspersio"]
,["","BS Sacrimenti"]
,["","Sanctuary"]
,["","Status Recovery"]
,["","Slow Poison"]
,["","Ressurection"]
,["","Kyrie Eleison"]
,["","Magnificat"]
,["","Gloria"]
,["","Lex Divina"]
,["","Turn Undead"]
,["","Lex Aeterna"]
,["","Magnus Exorcismus"]
,["","Skid Trap"]
,["","Land Mine"]
,["","Ankle Snare"]
,["","Flasher"]
,["","Shockwave Trap"]
,["","Sandman"]
,["","Freezing Trap"]
,["","Blast Mine"]
,["","Claymore Trap"]
,["","Remove Trap"]
,["","Talkie Box"]
,["","Beast Bane"]
,["","Falconry Mastery"]
,["","Blitz Beat"]
,["","Steel Crow"]
,["","Detect"]
,["","Spring Trap"]
,["","Fire Pillar"]
,["","Sense"]
,["","Sightrasher"]
,["","Meteor Storm"]
,["","Jupitel Thunder"]
,["","Lord of Vermillion"]
,["","Water Ball"]
,["","Ice Wall"]
,["","Frost Nova"]
,["","Storm Gust"]
,["","Earth Spike"]
,["","Heaven's Drive"]
,["","Quagmire"]
,["","Iron Tempering"]
,["","Steel Tempering"]
,["","Enchantedstone Craft"]
,["","Oridecon Research"]
,["","Smith Dagger"]
,["","Smith Sword"]
,["","Smith Two-handed Sword"]
,["","Smith Axe"]
,["","Smith Mace"]
,["","Smith Knucklebrace"]
,["","Smith Spear"]
,["","Hilt Binding"]
,["","Ore Discovery"]
,["","Weaponry Research"]
,["","Weapon Repair"]
,["","Skin Tempering"]
,["","Hammer Fall"]
,["","Andrenaline Rush"]
,["","Weapon Perfection"]
,["","Power-Thrust"]
,["","Power Maximize"]
,["","Faith"]
,["","Guard"]
,["","Smite"]
,["","Shield Boomerang"]
,["","Shield Reflect"]
,["","Holy Cross"]
,["","Grand Cross"]
,["","Sacrifice"]
,["","Resistant Souls"]
,["","Defending Aura"]
,["","Spear Quicken"]
,["","Snatch"]
,["","Mug"]
,["","Back Stab"]
,["","Stalk"]
,["","Sightless Mind"]
,["","Divest Weapon"]
,["","Divest Shield"]
,["","Divest Armor"]
,["","Divest Helm"]
,["","Gank"]
,["","Scribble"]
,["","Piece"]
,["","Remover"]
,["","Slyness"]
,["","Haggle"]
,["","Intimidate"]
,["","Iron Fists"]
,["","Spiritual Cadence"]
,["","Summon Spirit Sphere"]
,["","Spiritual Sphere Absorption"]
,["","Raging Trifecta Blow"]
,["","Raging Quadruple Blow"]
,["","Raging Thrust"]
,["","Snap"]
,["","Flee"]
,["","Throw Spirit Spheres"]
,["","Occult Impaction"]
,["","Root"]
,["","Fury"]
,["","Mental Strength"]
,["","Guillotine Fist"]
,["","Music Lessons"]
,["","Melody Strike"]
,["","Unchained Serenade"]
,["","Unbarring Octave"]
,["","Perfect Tablature"]
,["","Impressive Rift"]
,["","Magic Strings"]
,["","Song of Lutie"]
,["","Dance Lessons"]
,["","Slinging Arrow"]
,["","Hip Shaker"]
,["","Dazzler"]
,["","Focus Ballet"]
,["","Slow Grace"]
,["","Lady Luck"]
,["","Gypsy's Kiss"]
,["","Amp"]
,["","Encore"]
,["","Lullaby"]
,["","Mental Sensing"]
,["","Down Tempo"]
,["","Battle Theme"]
,["","Harmonic Lick"]
,["","Classical Pluck"]
,["","Power Cord"]
,["","Acoustic Rhythm"]
,["","Study"]
,["","Cast Cancel"]
,["","Magic Rod"]
,["","Spell Breaker"]
,["","Free Cast (N/A)"]
,["","Hindsight (N/A)"]
,["","Endow Blaze"]
,["","Endow Tsunami"]
,["","Endow Tornado"]
,["","Endow Quake"]
,["","Dragonology"]
,["","Volcano"]
,["","Deluge"]
,["","Whirlwind"]
,["","Magnetic Earth"]
,["","Dispell"]
,["","Hocus Pocus"]
,["","Axe Mastery"]
,["","Potion Research"]
,["","Prepare Potion"]
,["","Acid Terror"]
,["","Potion Pitcher"]
,["","Summon Flora"]
,["","Summon Marine Sphere"]
,["","Bomb"]
,["","Alchemical Weapon"]
,["","Synthesized Shield"]
,["","Synthetic Armor"]
,["","Biochemical Helm"]
,["","Fury (Super Novice)"]
,["","Aura Blade"]
,["","Parrying"]
,["","Spear Dynamo"]
,["","Tension Relax"]
,["","Frenzy"]
,["","Clashing Spiral"]
,["","Traumatic Blow"]
,["","Vital Strike"]
,["","Advanced Katar Mastery"]
,["","Soul Destroyer"]
,["","Meteor Assault"]
,["","Create Deadly Poison"]
,["","Enchant Deadly Poison"]
,["","Assumptio"]
,["","Basilica"]
,["","Mediatio"]
,["","Falcon Eyes"]
,["","Falcon Assault"]
,["","Focused Arrow Strike"]
,["","Wind Walk"]
,["","Soul Drain"]
,["","Stave Crasher"]
,["","Mystical Amplification"]
,["","Napalm Vulcan"]
,["","Shattering Strike"]
,["","Coin Craft"]
,["","Nugget Craft"]
,["","Cart Boost"]
,["","Battle Machine Craft"]
,["","Gloria Domini"]
,["","Martyr's Reconing"]
,["","Battle Chant"]
,["","Stealth (STR+)"]
,["","Counter Instinct"]
,["","Raging Palm Strike"]
,["","Glacier Fist"]
,["","Chain Crush Combo"]
,["","Zen"]
,["","Arrow Vulcan"]
,["","Sheltering Bliss"]
,["","Marionette Control"]
,["","Indulge"]
,["","Soul Exhale"]
,["","Soul Siphon"]
,["","Mind Breaker"]
,["","Alchemy"]
,["","Potion Synthesis"]
,["","Trifecta Delay Calculation"]
,["","Tomahawk Throwing"]
,["","Pulse Strike (Temp)"]
,["","Berserk Potion Pitcher"]
,["","Flying Kick (Sprint on)"]
,["","Venom Knife"]
,["","Phantasmic Arrow"]
,["","Charge Attack"]
,["","No death bonus"]
,["","Marriage Status -1"]
,["","Blacksmith Lv3 Number"]
,["","Dark Strike"]
,["","Fiber Lock"]
,["","Elemental Change"]
,["",""]
,["",""]
,["","Heat"]
,["","Heat (Wall)"]
,["","Heaven's Drive"]
,["","Water Ball"]
,["","Guillotine Fist (MaxSP-1)"]
,["","Foresight"]
,["","Deadly Poison (Consumed)"]
,["","Rapid Smiting"]
,["","Gravitational Field"]
,["","High Speed Cart Ram"]
,["","Maximum Power-Thust"]
,["","Acid Demonstration"]
,["","Sprint"]
,["","Tornado Stance"]
,["","Tornado Kick"]
,["","Heel Drop Stance"]
,["","Heel Drop"]
,["","Roundhouse Stance"]
,["","Roundouse"]
,["","Counter Kick Stance"]
,["","Counter Kick"]
,["","Tumbling (Untested)"]
,["","Flying Kick (Normal)"]
,["","Peaceful Break"]
,["","Happy Break"]
,["","Kihop"]
,["","Leap"]
,["","Taekwon Mission"]
,["","Taekwon Ranker"]
,["","Mild Wind"]
,["","Solar, Lunar, and Stellar Perception"]
,["","Solar Heat"]
,["","Lunar Heat"]
,["","Stellar Heat"]
,["","Solar, Lunar, and Stellar Opposition"]
,["","Solar Wrath"]
,["","Lunar Wrath"]
,["","Stellar Wrath"]
,["","Solar Protection"]
,["","Lunar Protection"]
,["","Stellar Protection"]
,["","Solar Blessings"]
,["","Lunar Blessings"]
,["","Stellar Blessings"]
,["","S.L.S. Shadow"]
,["","S.L.S. Team-Up"]
,["","S.L.S. Courier"]
,["","S.L.S. Union"]
,["","S.L.S. Miracle"]
,["","S.L.S. Angel"]
,["","S.L.S. Blessings"]
,["","Kaizel"]
,["","Kaahi"]
,["","Kaupe"]
,["","Kaite"]
,["","Kaina"]
,["","Estin"]
,["","Estun"]
,["","Esma"]
,["","Eswoo"]
,["","Eska"]
,["","Eske"]
,["","Sprint State"]
,["","Party Members (Kihop)"]
,["","Sonic Acceleration"]
,["","Excruciating Palm"]
,["","Close Confine"]
,["","Shield Boomerang (Soul Linked)"]
,["","Super Novice Spirit (Soul Link)"]
,["","One Hand Quicken (Soul Linked)"]
,["","Holy Light (Soul Linked)"]
,["","Sonic Blow (Soul Linked)"]
,["","Full Andrenaline Rush"]
,["","Hunter Spirit (Soul Link)"]
,["","Beast Strafing"]
,["","1st Transcendent Spirit"]
,["","Dagger Throwing Practice"]
,["","Throw Dagger"]
,["","Throw Kunai"]
,["","Throw Huuma Shuriken"]
,["","Throw Coins"]
,["","Flip Tatami"]
,["","Shadow Leap"]
,["","Haze Slasher"]
,["","Shadow Slash"]
,["","Cicada Skin Shed"]
,["","Mirror Image"]
,["","Ninja Aura"]
,["","Killing Stroke"]
,["","Ninja Mastery"]
,["","Flaming Petals"]
,["","Blaze Shield"]
,["","Exploding Dragon"]
,["","Freezing Spear"]
,["","Watery Evasion"]
,["","Snow Flake Draft"]
,["","Wind Blade"]
,["","Lightning Jolt"]
,["","First Wind"]
,["","Coin Flip"]
,["","Coin Fling"]
,["","Triple Action"]
,["","Bull's Eye"]
,["","Last Stand"]
,["","Gunslinger's Panic"]
,["","Increase Accuracy"]
,["","Magical Bullet"]
,["","Cracker"]
,["","Single Action"]
,["","Snake Eyes"]
,["","Chain Action"]
,["","Trigger Happy Shot"]
,["","Desperado (Single Hit)"]
,["","Tracking"]
,["","Disarm"]
,["","Wounding Shot"]
,["","Gatling Fever"]
,["","Crowd Control Shot"]
,["","Full Blast"]
,["","Spread Shot"]
,["","Gunslinger Mine"]
,["","Killing Stroke (MaxHP-1)"]
,["","Power Up"]
,["","Agi Up"]
,["","Change to Element"]
,["","Stone Skin"]
,["","Anti Magic"]
,["","Keeping"]
,["","Enchant Blade"]
,["","Sonic Wave"]
,["","Death Bound"]
,["","Hundred Spear"]
,["","Wind Cutter"]
,["","Ignition Break"]
,["","Phantom Thrust"]
,["","Dragon Training"]
,["","Dragon Breath"]
,["","Dragon Howling"]
,["","Rune Mastery"]
,["","Giant Growth"]
,["","Vitality Activation"]
,["","Storm Blast"]
,["","Stonehard Skin"]
,["","Fighting Spirit"]
,["","Abundance"]
,["","Crush Strike"]
,["","Refresh"]
,["","Millenium Shield"]
,["","Venom Impress"]
,["","Cross Impact"]
,["","Dark Illusion"]
,["","Research New Poison"]
,["","Create New Poison"]
,["Antidote","Antidote"]
,["Poisoning Weapon","Poisoning Weapon"]
,["Weapon Blocking","Weapon Blocking"]
,["Counter Slash","Counter Slash"]
,["Weapon Crush","Weapon Crush"]
,["Venom Pressure","Venom Pressure"]
,["Poison Smoke","Poison Smoke"]
,["Cloaking Exceed","Cloaking Exceed"]
,["Phantom Menace","Phantom Menace"]
,["Hallucination Walk","Hallucination Walk"]
,["Rolling Cutter","Rolling Cutter"]
,["Cross Ripper Slasher","Cross Ripper Slasher"]
,["Poison Paralyze","Poison Paralyze"]
,["Poison Pyrexia","Poison Pyrexia"]
,["Poison Disheart","Poison Disheart"]
,["Poison Leech End","Poison Leech End"]
,["Poison Venom Bleed","Poison Venom Bleed"]
,["Poison Magic Mushroom","Poison Magic Mushroom"]
,["Poison Toxin","Poison Toxin"]
,["Poison Oblivion Curse","Poison Oblivion Curse"]
,["Judex","Judex"]
,["Ancilla","Ancilla"]
,["Adoramus","Adoramus"]
,["Clementia","Clementia (bonus)"]
,["Canto Candidus","Canto Candidus (bonus)"]
,["Coluceo Heal","Coluceo Heal"]
,["Epiclesis","Epiclesis"]
,["Praefatio","Praefatio"]
,["Oratio","Oratio"]
,["Lauda Agnus","Lauda Agnus"]
,["Lauda Ramus","Lauda Ramus"]
,["Eucharistica","Eucharistica"]
,["Renovatio","Renovatio"]
,["Highness Heal","Highness Heal"]
,["Clearance","Clearance"]
,["Expiatio","Expiatio"]
,["Duple Light","Duple Light"]
,["Silentium","Silentium"]
,["Sacrament","Sacrament"]
,["Ranger Main","Ranger Main"]
,["Camouflage","Camouflage"]
,["Aimed Bolt","Aimed Bolt"]
,["Arrow Storm","Arrow Storm"]
,["Fear Breeze","Fear Breeze"]
,["Detonator","Detonator"]
,["Fire Trap","Fire Trap"]
,["Ice Trap","Ice Trap"]
,["Electric Shocker","Electric Shocker"]
,["Research Trap","Research Trap"]
,["Margenta Trap","Margenta Trap"]
,["Cobalt Trap","Cobalt Trap"]
,["Maize Trap","Maize Trap"]
,["Verdure Trap","Verdure Trap"]
,["Cluster Bomb","Cluster Bomb"]
,["Warg Mastery","Warg Mastery"]
,["Warg Rider","Warg Rider"]
,["Warg Dash","Warg Dash"]
,["Warg Bite","Warg Bite"]
,["Tooth of Warg","Tooth of Warg"]
,["Warg Strike","Warg Strike"]
,["Keen Nose","Keen Nose"]
,["Reading Spellbook","Reading Spellbook"]
,["Freezing Spell","Freezing Spell"]
,["Radius","Radius"]
,["Drain Life","Drain Life"]
,["Soul Expansion","Soul Expansion"]
,["White Imprison","White Imprison"]
,["Stasis","Stasis"]
,["Recognized Spell","Recognized Spell"]
,["Marsh of Abyss","Marsh of Abyss"]
,["Crimson Rock","Crimson Rock"]
,["Hell Inferno","Hell Inferno"]
,["Comet","Comet"]
,["Frosty Misty","Frosty Misty"]
,["Jack Frost","Jack Frost"]
,["Chain Lightning","Chain Lightning"]
,["Sienna Execrate","Sienna Execrate"]
,["Earth Strain","Earth Strain"]
,["Release","Release"]
,["Summon Fire Ball","Summon Fire Ball"]
,["Summon Water Ball","Summon Water Ball"]
,["Summon Lightning Ball","Summon Lightning Ball"]
,["Summon Stone","Summon Stone"]
,["Tetra Vortex","Tetra Vortex"]
,["Axe Training","Axe Mastery"]
,["Axe Tornado","Axe Tornado"]
,["Axe Boomerang","Axe Boomerang"]
,["Power Swing","Power Swing"]
,["Research Fire Earth","Fire & Earth Research"]
,["FAW Silver Sniper","FAW Silver Sniper"]
,["FAW Magic Decoy","FAW Magic Decoy"]
,["FAW Removal","Divest FAW"]
,["Magic Gear License","Mado Gear License"]
,["Repair","Repair"]
,["Acceleration","Acceleration"]
,["Hovering","Hovering"]
,["Front Side Slide","Front Slide"]
,["Back Side Slide","Back Slide"]
,["Boost Knuckle","Knuckle Boost"]
,["Pile Bunker","Pile Bunker"]
,["Vulcan Arm","Vulcan Arm"]
,["Flame Launcher","Flame Launcher"]
,["Cold Slower","Ice Launcher"]
,["Arm Cannon","Arm Cannon"]
,["Mainframe Restructure"," Remodel Mainframe"]
,["Self Destruction","Suicidal Destruction"]
,["Emergency Cool","Cooldown"]
,["Magnetic Field","Magnetic Field"]
,["Neutral Barrier","Neutral Barrier"]
,["Shape Shift","Elemental Shift"]
,["Infrared Scan","Infrared Scan"]
,["Analyze","Analyze"]
,["Stealth Field","Stealth Field"]
,["Spear Cannon","Spear Cannon"]
,["Vanishing Point","Vanishing Point"]
,["Trample","Trample"]
,["Shield Press","Shield Press"]
,["Reflect Damage","Reflect Damage"]
,["Pinpoint Attack","Pinpoint Attack"]
,["Force of Vanguard","Force of Vanguard"]
,["Rage Burst","Rage Burst"]
,["Shield Spell","Shield Spell"]
,["Exceed Break","Exceed Break"]
,["Overbrand","Overbrand"]
,["Prestige","Prestige"]
,["Banding","Banding"]
,["Moon Slasher","Moon Slasher"]
,["Ray of Genesis","Ray of Genesis"]
,["Piety","Piety"]
,["Earth Drive","Earth Drive"]
,["Hesperus Lit","Hesperus Lit"]
,["Inspiration","Inspiration"]
,["Fatal Menace","Fatal Menace"]
,["Reproduce","Reproduce"]
,["Auto Shadow Spell","Auto Shadow Spell"]
,["Shadow Form","Shadow Form"]
,["Triangle Shot","Triangle Shot"]
,["Strip Accessory","Strip Accessory"]
,["Invisibility","Invisibility"]
,["Deadly Infect","Deadly Infect"]
,["Body Painting","Body Painting"]
,["Masquerade Enervation","Masquerade Enervation"]
,["Masquerade Gloomy","Masquerade Gloomy"]
,["Masquerade Ignorance","Masquerade Ignorance"]
,["Masquerade Laziness","Masquerade Laziness"]
,["Masquerade Weakness","Masquerade Weakness"]
,["Masquerade Unlucky","Masquerade Unlucky"]
,["Man Hole","Man Hole"]
,["Dimension Door","Dimension Door"]
,["Chaos Panic","Chaos Panic"]
,["Maelstrom","Maelstrom"]
,["Bloody Lust","Bloody Lust"]
,["Feint Bomb","Feint Bomb"]
,["Dragon Combo","Dragon Combo"]
,["Sky Net Blow","Sky Net Blow"]
,["Earth Shaker","Earth Shaker"]
,["Rampage Blaster","Rampage Blaster"]
,["Knuckle Arrow","Knuckle Arrow"]
,["Fallen Empire","Fallen Empire"]
,["Tiger Cannon","Tiger Cannon"]
,["Gate of Hell","Gate of Hell"]
,["Crescent Elbow","Crescent Elbow"]
,["Windmill","Windmill"]
,["Cursed Circle","Cursed Circle"]
,["Lightning Walk","Lightning Walk"]
,["Rising Dragon","Rising Dragon"]
,["","Lion Howling"]
,["","Lightning Ride"]
,["","Gentle Touch Silence"]
,["Gentle Touch Cure","Gentle Touch Cure"]
,["Gentle Touch Energy Gain","Gentle Touch Energy Gain"]
,["Gentle Touch Change","Gentle Touch Convert"]
,["Gentle Touch Revitalize","Gentle Touch Revitalize"]
,["","Power Absorb"]
,["","Power Implantation"]
,["Windmill Rush","Windmill Rush"]
,["Echo Song","Echo Song"]
,["Harmonize","Harmonize"]
,["Swing Dance","Swing Dance"]
,["Lover's Symphony","Lover's Symphony"]
,["Moonlight Serenade","Moonlight Serenade"]
,["Voice Lessons","Voice Lessons"]
,["Reverberation","Reverberation"]
,["Dominion Impulse","Dominion Impulse"]
,["Metallic Sound","Metallic Sound"]
,["Great Echo","Great Echo"]
,["Severe Rainstorm","Severe Rainstorm"]
,["Deep Sleep Lullaby","Deep Sleep Lullaby"]
,["Song of Despair","Song of Despair"]
,["Improvised Song","Improvised Song"]
,["Gloomy Day","Gloomy Day"]
,["Siren's Voice","Siren's Voice"]
,["Circling Nature","Circling Nature"]
,["Death Valley","Death Valley"]
,["Dances With Wargs","Dances With Wargs"]
,["Saturday Night Fever","Saturday Night Fever"]
,["Destruction Song","Destruction Song"]
,["Lerad's Dew","Lerad's Dew"]
,["Warcry from Beyond","Warcry from Beyond"]
,["Infinite Humming","Infinite Humming"]
,["Song of Mana","Song of Mana"]
,["Sinking Melody","Sinking Melody"]
,["Fire Walk","Fire Walk"]
,["Electric Walk","Electric Walk"]
,["Spell Fist FBolt","Spell Fist (Fire Bolt)"]
,["Spell Fist CBolt","Spell Fist (Cold Bolt)"]
,["Spell Fist LBolt","Spell Fist (Lightning Bolt)"]
,["Vacuum Extreme","Vacuum Extreme"]
,["Psychic Wave","Psychic Wave"]
,["Cloud Kill","Cloud Kill"]
,["Poison Burst","Poison Burst"]
,["Striking","Striking"]
,["Earth Grave","Earth Grave"]
,["Diamond Dust","Diamond Dust"]
,["Warmer","Warmer"]
,["Varetyr Spear","Varetyr Spear"]
,["Arrullo","Arrullo"]
,["Sword Training","Sword Training"]
,["Cart Remodeling","Cart Remodeling"]
,["Cart Tornado","Cart Tornado"]
,["Cart Cannon","Cart Cannon"]
,["Cart Boost","Cart Boost"]
,["Thorn Trap","Thorn Trap"]
,["Blood Sucker","Blood Sucker"]
,["Spore Explosion","Spore Explosion"]
,["Wall Of Thorns","Wall Of Thorns"]
,["Crazy Weed","Crazy Weed"]
,["Demonic Fire","Demonic Fire"]
,["Fire Expansion","Fire Expansion"]
,["Hells Plant","Hells Plant"]
,["Howling of Mandragora","Howling of Mandragora"]
,["Sling Item","Sling Item"]
,["Change Material","Change Material"]
,["Mix Cooking","Mix Cooking"]
,["Create Bomb","Create Bomb"]
,["Special Pharmacy","Special Pharmacy"]
,["Spirit Control","Spirit Control"]
,["Summon Agni","Summon Agni"]
,["Summon Ventus","Summon Ventus"]
,["Summon Aqua","Summon Aqua"]
,["Summon Terra","Summon Terra"]
,["Fire Insignia","Fire Insignia"]
,["Wind Insignia","Wind Insignia"]
,["Water Insignia","Water Insignia"]
,["Earth Insignia","Earth Insignia"]
,["Summon Type","Summon Type"]
,["Summon Level","Summon Level"]
,["","Shield Spell (Physical)"]
,["","Shield Spell (Magical)"]
,["","Royal Guards (Party)"]
,["","Overbrand (Old Formula)"]
,["Odin's Power","Odin's Power"]
,["Fiber Lock","Fiber Lock"]
,["Overthrow","Overthrow"]
,["Cross Strike","Cross Strike"]
,["16th Night","16th Night"]
,["Spin Throw Kunai","Spin Throw Kunai"]
,["Spirit Breaker","Spirit Breaker"]
,["Huuma shuriken Strike","Huuma shuriken Strike"]
,["Throw Explosive Kunai","Throw Explosive Kunai"]
,["Summon Elemental Seal","Summon Elemental Seal"]
,["Seals Element","Seals element"]
,["","Dragon Water Breath"]
,["","Dark Claw"]
,["","Offertorium"]
,["","No Limits"]
,["","Intense Telekinesis"]
,["","Lava Flow"]
,["","King's Grace"]
,["","Emergency Escape"]
,["","Flash Combo"]
,["","Frigg's Song"]
,["","Elemental Shield"]
,["","Hallucination Drug"]
,["","Full Throttle"]
];
}
