{ // WeaponTypes [WeaponName]
WeaponName = [
[" }Kb","Unarmed"]
,["�wcR","Dagger"]
,["GrKbcR","One-handed Sword"]
,["!NKbcR","Two-handed Sword"]
,["GrKb�i","One-handed Spear"]
,["!NKb�i","Two-handed Spear"]
,["GrKb�e","One-handed Axe"]
,["!NKb�e","Two-handed Axe"]
,["hV","Mace"]
,["Vg","Rod (One and two-handed)"]
,["_","Bow"]
,["�0�0�0�0","Katar"]
,[",g","Book"]
,["�0�0�0�0","Knuckle"]
,["}ihV","Instrument"]
,["��","Whip"]
,["��T�KbψcR","Huuma Shuriken"]
,["�0�0�0�0�0","Handgun"]
,["�0�0�0�0","Rifle"]
,["�0�0�0�0�0�0","Shotgun"]
,["�0�0�0�0�0�0�0","Gatling Gun"]
,["�0�0�0�0�0�0�0","Grenade Launcher"]
];
}
