#![allow(dead_code)]

pub enum StatusTypes {
    None,
    Speed,
    Baseexp,
    Jobexp,
    Karma,
    Manner,
    Hp,
    Maxhp,
    Sp,
    Maxsp,
    Statuspoint,
    Baselevel,
    Skillpoint,
    Str,
    Agi,
    Vit,
    Int,
    Dex,
    Luk,
    Class,
    Zeny,
    Sex,
    Nextbaseexp,
    Nextjobexp,
    Weight,
    Maxweight,
    Ustr,
    Uagi,
    Uvit,
    Uint,
    Udex,
    Uluk,
    Atk1,
    Atk2,
    Matk1,
    Matk2,
    Def1,
    Def2,
    Mdef1,
    Mdef2,
    Hit,
    Flee1,
    Flee2,
    Critical,
    Aspd,
    Joblevel,
    Upper,
    Partner,
    Cart,
    Fame,
    Unbreakable,
    Cartinfo,
    Basejob,
    Baseclass,
    Killerrid,
    Killedrid,
    Slotchange,
    Charrename,
    Modexp,
    Moddrop,
    Moddeath,
    Bankvault,
    Mercflee,
    Merckills,
    Mercfaith,
    Pow,
    Sta,
    Wis,
    Spl,
    Con,
    Crt,
    Patk,
    Smatk,
    Res,
    Mres,
    Hplus,
    Crate,
    Tstatuspoint,
    Ap,
    Maxap,
    Upow,
    Usta,
    Uwis,
    Uspl,
    Ucon,
    Ucrt,
    Attackrange,
    Atkele,
    Defele,
    Castrate,
    Maxhprate,
    Maxsprate,
    Sprate,
    Addele,
    Addrace,
    Addsize,
    Subele,
    Subrace,
    Addeff,
    Reseff,
    Baseatk,
    Aspdrate,
    Hprecovrate,
    Recovrate,
    Speedrate,
    Criticaldef,
    Nearatkdef,
    Longatkdef,
    Doublerate,
    Doubleaddrate,
    Skillheal,
    Matkrate,
    Ignoredefele,
    Ignoredefrace,
    Atkrate,
    Speedaddrate,
    Regenrate,
    Magicatkdef,
    Miscatkdef,
    Ignoremdefele,
    Ignoremdefrace,
    Magicaddele,
    Magicaddrace,
    Magicaddsize,
    Perfecthitrate,
    Perfecthitaddrate,
    Criticalrate,
    Getzenynum,
    Addgetzenynum,
    Adddamageclass,
    Addmagicdamageclass,
    Adddefclass,
    Addmdefclass,
    Addmonsterdropitem,
    Defratioatkele,
    Defratioatkrace,
    Unbreakablegarment,
    Hitrate,
    Fleerate,
    Flee2Rate,
    Defrate,
    Def2Rate,
    Mdefrate,
    Mdef2Rate,
    Splashrange,
    Splashaddrange,
    Autospell,
    Hpdrainrate,
    Drainrate,
    Shortweapondamagereturn,
    Longweapondamagereturn,
    Weaponcomaele,
    Weaponcomarace,
    Addeff2,
    Breakweaponrate,
    Breakarmorrate,
    Addstealrate,
    Magicdamagereturn,
    Allstats,
    Agivit,
    Agidexstr,
    Perfecthide,
    Noknockback,
    Classchange,
    Hpdrainvalue,
    Drainvalue,
    Weaponatk,
    Weaponatkrate,
    Delayrate,
    Hpdrainraterace,
    Drainraterace,
    Ignoremdefrate,
    Ignoredefrate,
    Skillheal2,
    Addeffonskill,
    Addhealrate,
    Addheal2Rate,
    Hpvanishrate,
    Restartfullrecover,
    Nocastcancel,
    Nosizefix,
    Nomagicdamage,
    Noweapondamage,
    Nogemstone,
    Nocastcancel2,
    Nomiscdamage,
    Unbreakableweapon,
    Unbreakablearmor,
    Unbreakablehelm,
    Unbreakableshield,
    Longatkrate,
    Critatkrate,
    Criticaladdrace,
    Noregen,
    Addeffwhenhit,
    Autospellwhenhit,
    Skillatk,
    Unstripable,
    Autospellonskill,
    Gainvalue,
    Hpregenrate,
    Hplossrate,
    Addrace2,
    Hpgainvalue,
    Subsize,
    Hpdrainvaluerace,
    Additemhealrate,
    Drainvaluerace,
    Expaddrace,
    Gainrace,
    Subrace2,
    Unbreakableshoes,
    Unstripableweapon,
    Unstripablearmor,
    Unstripablehelm,
    Unstripableshield,
    Intravision,
    Addmonsterdropchainitem,
    Lossrate,
    Addskillblow,
    Vanishrate,
    Magicgainvalue,
    Magichpgainvalue,
    Addclassdropitem,
    Ematk,
    Gainraceattack,
    Hpgainraceattack,
    Skilluserate,
    Skillcooldown,
    Skillfixedcast,
    Skillvariablecast,
    Fixcastrate,
    Varcastrate,
    Skillusesp,
    Magicatkele,
    Addfixedcast,
    Addvariablecast,
    Setdefrace,
    Setmdefrace,
    Racetolerance,
    Addmaxweight,
    Subdefele,
    Magicsubdefele,
    Statenorecoverrace,
}

impl StatusTypes {
    pub fn value(&self) -> u32 {
        match *self {
            StatusTypes::None => u32::MAX,
            StatusTypes::Speed => 0,
            StatusTypes::Baseexp => 1,
            StatusTypes::Jobexp => 2,
            StatusTypes::Karma => 3,
            StatusTypes::Manner => 4,
            StatusTypes::Hp => 5,
            StatusTypes::Maxhp => 6,
            StatusTypes::Sp => 7,
            StatusTypes::Maxsp => 8,
            StatusTypes::Statuspoint => 9,
            StatusTypes::Baselevel => 11,
            StatusTypes::Skillpoint => 12,
            StatusTypes::Str => 13,
            StatusTypes::Agi => 14,
            StatusTypes::Vit => 15,
            StatusTypes::Int => 16,
            StatusTypes::Dex => 17,
            StatusTypes::Luk => 18,
            StatusTypes::Class => 19,
            StatusTypes::Zeny => 20,
            StatusTypes::Sex => 21,
            StatusTypes::Nextbaseexp => 22,
            StatusTypes::Nextjobexp => 23,
            StatusTypes::Weight => 24,
            StatusTypes::Maxweight => 25,
            StatusTypes::Ustr => 32,
            StatusTypes::Uagi => 33,
            StatusTypes::Uvit => 34,
            StatusTypes::Uint => 35,
            StatusTypes::Udex => 36,
            StatusTypes::Uluk => 37,
            StatusTypes::Atk1 => 41,
            StatusTypes::Atk2 => 42,
            StatusTypes::Matk1 => 43,
            StatusTypes::Matk2 => 44,
            StatusTypes::Def1 => 45,
            StatusTypes::Def2 => 46,
            StatusTypes::Mdef1 => 47,
            StatusTypes::Mdef2 => 48,
            StatusTypes::Hit => 49,
            StatusTypes::Flee1 => 50,
            StatusTypes::Flee2 => 51,
            StatusTypes::Critical => 52,
            StatusTypes::Aspd => 53,
            StatusTypes::Joblevel => 55,
            StatusTypes::Upper => 56,
            StatusTypes::Partner => 57,
            StatusTypes::Cart => 58,
            StatusTypes::Fame => 59,
            StatusTypes::Unbreakable => 60,
            StatusTypes::Cartinfo => 99,
            StatusTypes::Basejob => 119,
            StatusTypes::Baseclass => 120,
            StatusTypes::Killerrid => 121,
            StatusTypes::Killedrid => 122,
            StatusTypes::Slotchange => 123,
            StatusTypes::Charrename => 124,
            StatusTypes::Modexp => 125,
            StatusTypes::Moddrop => 126,
            StatusTypes::Moddeath => 127,
            StatusTypes::Bankvault => 128,

            // Mercenaries
            StatusTypes::Mercflee => 165,
            StatusTypes::Merckills => 189,
            StatusTypes::Mercfaith => 190,

            // 4th job update
            StatusTypes::Pow => 219,
            StatusTypes::Sta => 220,
            StatusTypes::Wis => 221,
            StatusTypes::Spl => 222,
            StatusTypes::Con => 223,
            StatusTypes::Crt => 224,
            StatusTypes::Patk => 225,
            StatusTypes::Smatk => 226,
            StatusTypes::Res => 227,
            StatusTypes::Mres => 228,
            StatusTypes::Hplus => 229,
            StatusTypes::Crate => 230,
            StatusTypes::Tstatuspoint => 231,
            StatusTypes::Ap => 232,
            StatusTypes::Maxap => 233,
            StatusTypes::Upow => 247,
            StatusTypes::Usta => 248,
            StatusTypes::Uwis => 249,
            StatusTypes::Uspl => 250,
            StatusTypes::Ucon => 251,
            StatusTypes::Ucrt => 252,

            // original 1000-
            StatusTypes::Attackrange => 1000,
            StatusTypes::Atkele => 1001,
            StatusTypes::Defele => 1002,
            StatusTypes::Castrate => 1003,
            StatusTypes::Maxhprate => 1004,
            StatusTypes::Maxsprate => 1005,
            StatusTypes::Sprate => 1006,
            StatusTypes::Addele => 1007,
            StatusTypes::Addrace => 1008,
            StatusTypes::Addsize => 1009,
            StatusTypes::Subele => 1010,
            StatusTypes::Subrace => 1011,
            StatusTypes::Addeff => 1012,
            StatusTypes::Reseff => 1013,
            StatusTypes::Baseatk => 1014,
            StatusTypes::Aspdrate => 1015,
            StatusTypes::Hprecovrate => 1016,
            StatusTypes::Recovrate => 1017,
            StatusTypes::Speedrate => 1018,
            StatusTypes::Criticaldef => 1019,
            StatusTypes::Nearatkdef => 1020,
            StatusTypes::Longatkdef => 1021,
            StatusTypes::Doublerate => 1022,
            StatusTypes::Doubleaddrate => 1023,
            StatusTypes::Skillheal => 1024,
            StatusTypes::Matkrate => 1025,
            StatusTypes::Ignoredefele => 1026,
            StatusTypes::Ignoredefrace => 1027,
            StatusTypes::Atkrate => 1028,
            StatusTypes::Speedaddrate => 1029,
            StatusTypes::Regenrate => 1030,
            StatusTypes::Magicatkdef => 1031,
            StatusTypes::Miscatkdef => 1032,
            StatusTypes::Ignoremdefele => 1033,
            StatusTypes::Ignoremdefrace => 1034,
            StatusTypes::Magicaddele => 1035,
            StatusTypes::Magicaddrace => 1036,
            StatusTypes::Magicaddsize => 1037,
            StatusTypes::Perfecthitrate => 1038,
            StatusTypes::Perfecthitaddrate => 1039,
            StatusTypes::Criticalrate => 1040,
            StatusTypes::Getzenynum => 1041,
            StatusTypes::Addgetzenynum => 1042,
            StatusTypes::Adddamageclass => 1043,
            StatusTypes::Addmagicdamageclass => 1044,
            StatusTypes::Adddefclass => 1045,
            StatusTypes::Addmdefclass => 1046,
            StatusTypes::Addmonsterdropitem => 1047,
            StatusTypes::Defratioatkele => 1048,
            StatusTypes::Defratioatkrace => 1049,
            StatusTypes::Unbreakablegarment => 1050,
            StatusTypes::Hitrate => 1051,
            StatusTypes::Fleerate => 1052,
            StatusTypes::Flee2Rate => 1053,
            StatusTypes::Defrate => 1054,
            StatusTypes::Def2Rate => 1055,
            StatusTypes::Mdefrate => 1056,
            StatusTypes::Mdef2Rate => 1057,
            StatusTypes::Splashrange => 1058,
            StatusTypes::Splashaddrange => 1059,
            StatusTypes::Autospell => 1060,
            StatusTypes::Hpdrainrate => 1061,
            StatusTypes::Drainrate => 1062,
            StatusTypes::Shortweapondamagereturn => 1063,
            StatusTypes::Longweapondamagereturn => 1064,
            StatusTypes::Weaponcomaele => 1065,
            StatusTypes::Weaponcomarace => 1066,
            StatusTypes::Addeff2 => 1067,
            StatusTypes::Breakweaponrate => 1068,
            StatusTypes::Breakarmorrate => 1069,
            StatusTypes::Addstealrate => 1070,
            StatusTypes::Magicdamagereturn => 1071,
            StatusTypes::Allstats => 1073,
            StatusTypes::Agivit => 1074,
            StatusTypes::Agidexstr => 1075,
            StatusTypes::Perfecthide => 1076,
            StatusTypes::Noknockback => 1077,
            StatusTypes::Classchange => 1078,
            StatusTypes::Hpdrainvalue => 1079,
            StatusTypes::Drainvalue => 1080,
            StatusTypes::Weaponatk => 1081,
            StatusTypes::Weaponatkrate => 1082,
            StatusTypes::Delayrate => 1083,
            StatusTypes::Hpdrainraterace => 1084,
            StatusTypes::Drainraterace => 1085,
            StatusTypes::Ignoremdefrate => 1086,
            StatusTypes::Ignoredefrate => 1087,
            StatusTypes::Skillheal2 => 1088,
            StatusTypes::Addeffonskill => 1089,
            StatusTypes::Addhealrate => 1090,
            StatusTypes::Addheal2Rate => 1091,
            StatusTypes::Hpvanishrate => 1092,
            StatusTypes::Restartfullrecover => 2000,
            StatusTypes::Nocastcancel => 2001,
            StatusTypes::Nosizefix => 2002,
            StatusTypes::Nomagicdamage => 2003,
            StatusTypes::Noweapondamage => 2004,
            StatusTypes::Nogemstone => 2005,
            StatusTypes::Nocastcancel2 => 2006,
            StatusTypes::Nomiscdamage => 2007,
            StatusTypes::Unbreakableweapon => 2008,
            StatusTypes::Unbreakablearmor => 2009,
            StatusTypes::Unbreakablehelm => 2010,
            StatusTypes::Unbreakableshield => 2011,
            StatusTypes::Longatkrate => 2012,
            StatusTypes::Critatkrate => 2013,
            StatusTypes::Criticaladdrace => 2014,
            StatusTypes::Noregen => 2015,
            StatusTypes::Addeffwhenhit => 2016,
            StatusTypes::Autospellwhenhit => 2017,
            StatusTypes::Skillatk => 2018,
            StatusTypes::Unstripable => 2019,
            StatusTypes::Autospellonskill => 2020,
            StatusTypes::Gainvalue => 2021,
            StatusTypes::Hpregenrate => 2022,
            StatusTypes::Hplossrate => 2023,
            StatusTypes::Addrace2 => 2024,
            StatusTypes::Hpgainvalue => 2025,
            StatusTypes::Subsize => 2026,
            StatusTypes::Hpdrainvaluerace => 2027,
            StatusTypes::Additemhealrate => 2028,
            StatusTypes::Drainvaluerace => 2029,
            StatusTypes::Expaddrace => 2030,
            StatusTypes::Gainrace => 2031,
            StatusTypes::Subrace2 => 2032,
            StatusTypes::Unbreakableshoes => 2033,
            StatusTypes::Unstripableweapon => 2034,
            StatusTypes::Unstripablearmor => 2035,
            StatusTypes::Unstripablehelm => 2036,
            StatusTypes::Unstripableshield => 2037,
            StatusTypes::Intravision => 2038,
            StatusTypes::Addmonsterdropchainitem => 2039,
            StatusTypes::Lossrate => 2040,
            StatusTypes::Addskillblow => 2041,
            StatusTypes::Vanishrate => 2042,
            StatusTypes::Magicgainvalue => 2043,
            StatusTypes::Magichpgainvalue => 2044,
            StatusTypes::Addclassdropitem => 2045,
            StatusTypes::Ematk => 2046,
            StatusTypes::Gainraceattack => 2047,
            StatusTypes::Hpgainraceattack => 2048,
            StatusTypes::Skilluserate => 2049,
            StatusTypes::Skillcooldown => 2050,
            StatusTypes::Skillfixedcast => 2051,
            StatusTypes::Skillvariablecast => 2052,
            StatusTypes::Fixcastrate => 2053,
            StatusTypes::Varcastrate => 2054,
            StatusTypes::Skillusesp => 2055,
            StatusTypes::Magicatkele => 2056,
            StatusTypes::Addfixedcast => 2057,
            StatusTypes::Addvariablecast => 2058,
            StatusTypes::Setdefrace => 2059,
            StatusTypes::Setmdefrace => 2060,
            StatusTypes::Racetolerance => 2061,
            StatusTypes::Addmaxweight => 2062,
            StatusTypes::Subdefele => 2063,
            StatusTypes::Magicsubdefele => 2064,
            StatusTypes::Statenorecoverrace => 2065,
        }
    }
}